In [7]:
import numpy as np

The Basics


In [6]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [5]:
b = np.array([[1, 2, 34], [7, 8, 9], [5, 6, 23]])
print(b)


[[ 1  2 34]
 [ 7  8  9]
 [ 5  6 23]]


In [11]:
#Get dimension
print(b.ndim)

2


In [12]:
# Get shape
b.shape

(3, 3)

In [13]:
a.dtype # Get type

dtype('int64')

In [15]:
# get size
b.itemsize

8

In [16]:
# get total size
b.nbytes

72

In [17]:
# get number of elements
b.size


9

Accessing/ Channging elements, rows, cols.....

In [19]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# get a specific element [i, j]
print(a[1,5])

13


In [26]:
#get whole row
print(a[1, :])

[ 8  9 10 11 12 13 14]


In [25]:
# get whole column
print(a[:, 4])

[ 5 12]


In [28]:
print(a[0, 1:6:2])  # [startindex:endindex:stepsize]    #startindex = 0, 1      endindex = 6 or(0, 6)   stepsize = 2

[2 4 6]


3d Example

In [29]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
#get specific element
print(b[0, 0, 1])

2


Initializing different types of arrays


In [33]:
# all 0 matrix
np.zeros((3, 4))   # 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
# all 1's matrix

np.ones((2, 3, 4), dtype='int32')   # 2 matrix of 3 rows and 4 columns

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [37]:
# any other number
np.full((3, 3), 101)

array([[101, 101, 101],
       [101, 101, 101],
       [101, 101, 101]])

In [38]:
# any other number (full_like)
np.full_like(a, 4)  # a like matrix with all 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [39]:
# random decimal numbers
np.random.rand(4, 2)    # 4 rows and 2 columns with random decimal numbers between 0 and 1

array([[0.11410272, 0.36210497],
       [0.7922656 , 0.56342714],
       [0.95498719, 0.7284476 ],
       [0.04225147, 0.09439944]])

In [40]:
# random integer values
np.random.randint(10, size=(3, 3))  # 3 rows and 3 columns with random integer values between 0 and 10

array([[2, 3, 5],
       [1, 5, 8],
       [3, 8, 0]], dtype=int32)

In [41]:
# identity matrix
np.identity(5)  # 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
# output = np.ones((5, 5))
# for i in range (1, 4):
#     output[i, 1: 4] = 0

# output[2, 2] = 9
# print(output)

output = np.ones((5, 5))
temp = np.zeros((3, 3))
temp[1, 1] = 9
output[1:4, 1:4] = temp
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
