In [7]:
import numpy as np

The Basics


In [6]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [5]:
b = np.array([[1, 2, 34], [7, 8, 9], [5, 6, 23]])
print(b)


[[ 1  2 34]
 [ 7  8  9]
 [ 5  6 23]]


In [11]:
#Get dimension
print(b.ndim)

2


In [12]:
# Get shape
b.shape

(3, 3)

In [13]:
a.dtype # Get type

dtype('int64')

In [15]:
# get size
b.itemsize

8

In [16]:
# get total size
b.nbytes

72

In [17]:
# get number of elements
b.size


9

Accessing/ Channging elements, rows, cols.....